<template>
  <h1>Weather</h1>
  <h2>Atmospheric Conditions</h2>
  <p>
    Weather is the state of the atmosphere at a specific time and place, with
    respect to temperature, precipitation, and other factors such as cloudiness.
    Weather is generated by many forces, some obvious, some not. Warm, humid air
    masses blowing in from oceans, for example, fuel rains. Sunlight heats the
    land, generating thermals that help produce summer thunderstorms.
  </p>

  <p>
    Mountains and cities also affect the weather. In mountains this occurs
    because the wind must rise as it crosses over the ridge. This lifts the air,
    causing it to cool. That produces clouds, rain, or snow.
  </p>

  <p>
    Cities, on the other hand, produce urban "heat islands" where roads, parking
    lots, and rooftops warm in the sun. This not only raises the city's
    temperature, but it can affect the weather, producing thunderstorms in some
    cities or altering storm tracks in others.
  </p>
  <h2>Predicting the Weather</h2>
  <p>
    Weather forecasting is the art of predicting what will happen in the future.
    In its simplest form, it's merely a matter of looking out the window to see
    what types of clouds are around and which way they are moving. Knowledge of
    local weather patterns can then allow fairly good predictions for the next
    12 to 24 hours.
  </p>

  <p>
    Professional forecasters have a wide variety of other tools. Weather
    stations scattered around the globe allow them to make detailed weather
    maps, as do satellites, which allow forecasters to see what is happening far
    out to sea, where there are no weather stations. Weather balloons and radar
    also contribute.
  </p>

  <p>
    Nevertheless, long-run weather forecasting is notoriously difficult. That's
    because weather prediction involves a mathematical concept called chaos
    theory, in which extremely small errors in measuring today's weather
    conditions can snowball into large, seemingly random, errors in long-range
    forecasts.
  </p>
</template>

<script>
export default {
  name: "Home",
};
</script>

<style scoped>
</style>